ProStages_index:
    path: /
    controller: App\Controller\StageController::index

ProStages_stageParEntreprise:
    path: /stageParEntreprise/{entreprise}
    controller: App\Controller\ProStagesController::stageParEntreprise

ProStages_stageParFormation:
    path: /stageParFormation/{formation}
    controller: App\Controller\ProStagesController::stageParFormation


ProStages_entreprises:
    path: /entreprises
    controller: App\Controller\ProStagesController::entreprises

ProStages_formations:
    path: /formations
    controller: App\Controller\ProStagesController::formations

ProStages_stages:
    path: /stages/{id}
    controller: App\Controller\ProStagesController::stages

ProStages_ajoutEntreprise:
    path: /entreprises/ajouter
    controller: App\Controller\ProStagesController::ajouterEntreprise

ProStages_modifierEntreprise:
    path: /entreprises/modifier/{id}
    controller: App\Controller\ProStagesController::modifierEntreprise
